[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "https://www.jason.af/posts/"
  status = 301

[[headers]]
  for = "/*"
  [headers.values]
    X-From = "lengstorf.com"
